services:
  vrituel_dressing_frontend:
    build: .
    container_name: dressing_virtuel_django
    ports: 
      - 8000:8000
    env_file:
      - config/.env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  # postgres:
  #   image: jhonatancaldeira/postgres_dressing-virtuel:latest
  #   ports:
  #     - 5432:5432
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5